name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose the version type (major, minor, or patch)'
        required: true

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Bump version and push tag
        run: |
          npm version ${{ github.event.inputs.version }}

      - name: Push changes
        run: |
          git push --follow-tags
